# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-13 12:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_auto_20171013_0932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='menu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='menu.Menu'),
        ),
        migrations.AlterField(
            model_name='link',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='menu.Link'),
        ),
    ]
